theme: minima
title: Corona virus en Colombia
author: aracely848
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write about the number of cases in Colombia with Corona Virus today in all its cities

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
